name: Playwright Tests

on:
  push:
    branches: [ main, dev ]

  pull_request:
    branches: [ main ]

  schedule:
    - cron: "30 18 * * *"

  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TEST_ENV: ${{ github.event.inputs.environment || 'qa' }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Extract Test Summary
        id: results
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          SUMMARY=$(cat allure-report/widgets/summary.json)

          TOTAL=$(echo $SUMMARY | jq '.statistic.total')
          PASSED=$(echo $SUMMARY | jq '.statistic.passed')
          FAILED=$(echo $SUMMARY | jq '.statistic.failed')

          if [ "$FAILED" -gt 0 ]; then
            STATUS="FAILED"
          else
            STATUS="PASSED"
          fi

          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "failed=$FAILED" >> $GITHUB_OUTPUT
          echo "status=$STATUS" >> $GITHUB_OUTPUT

      - name: Deploy Allure Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Send Execution Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: "[${{ env.TEST_ENV }}] Playwright Automation - ${{ steps.results.outputs.status }}"

          to: sr.yalluri@gmail.com
          from: Playwright Automation

          html_body: |
            <h2>Playwright Test Execution Report</h2>

            <p><b>Environment:</b> ${{ env.TEST_ENV }}</p>

            <table border="1" cellpadding="8">
              <tr>
                <th>Total</th>
                <th style="color:green;">Passed</th>
                <th style="color:red;">Failed</th>
              </tr>
              <tr>
                <td>${{ steps.results.outputs.total }}</td>
                <td>${{ steps.results.outputs.passed }}</td>
                <td>${{ steps.results.outputs.failed }}</td>
              </tr>
            </table>

            <br>

            <p>
            <b>Allure Report:</b><br>
            https://sryalluri.github.io/playwright-hybrid-framework/
            </p>

            <p>
            <b>GitHub Run:</b><br>
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            </p>